minimumReleaseAgeExclude:
  - '@erwanjugand/*'
allowBuilds:
  '@parcel/watcher': false
  cypress: true
  esbuild: true
  unrs-resolver: false
  workerd: false
  sharp: false
overrides:
  '@nuxt/vite-builder@4>vite': '^8.0.0' # Should no longer be necessary with Nuxt 5
  'vite-node@5>vite': '^8.0.0' # Should no longer be necessary with Nuxt 5
