minimumReleaseAgeExclude:
  - '@erwanjugand/*'
minimumReleaseAgeExcludePrune: true
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  unrs-resolver: false
  workerd: false
  sharp: false
  vue-demi: false
