name = "portfolio"
main = "./.output/server/index.mjs"
compatibility_date = "2023-03-01"

[site]
bucket = ".output/public"

[env.production]
name = "portfolio-prod"
route = "erwan-jugand.fr/*"

[env.dev]
name = "portfolio-dev"
route = "portfolio.erwan-jugand.workers.dev/*"
