name = "portfolio"
main = "./.output/server/index.mjs"
compatibility_date = "2023-03-01"

[site]
bucket = ".output/public"

[env.dev]
name = "portfolio-dev"
workers_dev = true

[env.prod]
route = "erwan-jugand.fr/*"
